name: Update Output

on: workflow_dispatch

permissions:
  contents: read
  pull-requests: write

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Use Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
        working-directory: ./getversions
      - name: Run tool
        run: bun run main.ts
        working-directory: ./getversions
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add getversions/output.json
          git commit -m "Update output"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
